config/routes.rb
Rails.application.routes.draw do

  root 'query_movie#query_movie'
  get 'welcome/index'

  post 'query_movie', to: 'query_movie#search_results'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/query_movie_controller.rb
class QueryMovieController < ApplicationController

  require 'net/http'
  require 'json'

  QUERY_URL = 'http://www.myapifilms.com/imdb'


  def query_movie
    @search = params[:search] || cookies[:form_name]
    @search2 = params[:search_type] || cookies[:form_type]
  end

  def search_results
    cookies[:form_name] = params[:search] if params[:search]
    cookies[:form_type] = params[:search_type] if params[:search_type]
    movie_title = cookies[:form_name]
    if movie_title.present?
      if cookies[:form_type] == "title"
#logger.debug "*****************"
#logger.debug cookies[:form_type]
#logger.debug "******************"
        uri = URI(QUERY_URL + "?title=#{URI.escape(movie_title)}")
      else
        uri = URI(QUERY_URL + "?name=#{URI.escape(movie_title)}&filmography=1")
      end
      imdb_info_json = Net::HTTP.get(uri)
      imdb_info_ruby = JSON.parse(imdb_info_json)
      @imdb_info_var = imdb_info_ruby.first
    end
    @search = params[:search] || cookies[:form_name]
    @search2 = params[:search_type] || cookies[:form_type]
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/query_movie_helper.rb
module QueryMovieHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnhApp</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

<%= yield %>

</body>
</html>

app/views/query_movie/query_movie.html.erb
<% if @search.present? %>
  <p>You previously searched for <%=@search2 %> <%= @search %>.  Click here to search for that again.</p>
  <%= button_to "run that same search again", query_movie_path, class: "btn btn-danger" %>
<% end %>

<p> Enter a search below <p>

<%= form_tag "query_movie" do %>
  <input type="text" name="search" value="<%= @search %>"/>
  <select name="search_type">
    <option value="title">Title</option>
    <option value="actor">Actor</option>
  </select>
  <input type="submit" value="Go"/>
<% end %>

app/views/query_movie/search_results.html.erb
<%= link_to "Root Path", root_path %>

<p> This is what the Cookie currently holds: Search Name =<%= @search %> and Search Type =<%= @search2 %><p>


<%= form_tag "query_movie" do %>
  How about you enter another search?
  <input type="text" name="search" value="<%= @search %>"/>
  <select name="search_type">
    <option value="title">Title</option>
    <option value="actor">Actor</option>
  </select>
  <input type="submit" value="Go"/>
<% end %>

<h1 class="search_results_title">Here's what i found! </h1>

<% if @search.present? %>
  <% if @search2 == "title" %>
<!--This is for a Movie Title search-->
    <div>
      <!--<a href="<%# @imdb_info_var["urlIMDB"] %>">-->
        <%= link_to image_tag(@imdb_info_var["urlPoster"]), @imdb_info_var["urlIMDB"], class: "movie_poster" %>
      </a>
      <h1>
      <!--<a href="<%= @imdb_info_var["urlIMDB"] %>" class="movie_title">-->
          <%= link_to "#{@imdb_info_var['title']} (#{@imdb_info_var["year"]})", @imdb_info_var["urlIMDB"], class: "movie_title" %>
        </a>
      </h1>
      <p class="movie_plot italicize"><%= @imdb_info_var["plot"] %> </p>
      <p class="movie_plot italicize"><%= @imdb_info_var["runtime"].first %><p>
    <div>
    <div>
      <p>Languages availalbe for the film:</p>
      <ul class="a movie_plot italicize">
        <% @imdb_info_var['languages'].each do |lang| %>
          <li><%= lang %> </li>
        <% end %>
      <ul>
    <div>
  <% else %>
<!--This is for an Actor's Name search-->
    <div>
      <img src="<%= @imdb_info_var["urlPhoto"] %>" style="width:250px;height:300px;float:left;margin: 20px">
      <h1 class="movie_title" style="color:red"><%= @imdb_info_var["name"]%></h1>
      <p class="movie_plot italicize"><%= @imdb_info_var["bio"] %><p>
    <div>
      <p>Actor Filmography:</p>
      <ul class="a movie_plot italicize">
        <% @imdb_info_var['filmographies'][0]['filmography'].each do |film| %>
          <li><%= film['title'] %> </li>
        <% end %>
      <ul>
    <div>
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to my Rails App!</h1>